services:
  postgres:
    image: postgres:16-alpine
    container_name: diplom-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cloud_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: diplom-backend
    depends_on:
      - postgres
      - ai-worker
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/cloud_storage
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yRGlwbG9tMjAyNg==
      STORAGE_ROOT: /app/storage
      STORAGE_QUOTA_BYTES: 1073741824
      AI_WORKER_URL: http://ai-worker:8090
      AI_WORKER_ENABLED: "true"
      CORS_ALLOWED_ORIGIN_PATTERN: http://localhost:*
    ports:
      - "8080:8080"
    volumes:
      - backend_storage:/app/storage

  ai-worker:
    build:
      context: ./ai-worker
      args:
        INSTALL_MODELS: ${INSTALL_MODELS:-true}
    container_name: diplom-ai-worker
    environment:
      MODEL_MODE: ${MODEL_MODE:-auto}
      TEXT_MODEL: ${TEXT_MODEL:-intfloat/multilingual-e5-small}
      IMAGE_MODEL: ${IMAGE_MODEL:-ViT-B-32}
      IMAGE_PRETRAINED: ${IMAGE_PRETRAINED:-laion400m_e32}
      OCR_ENABLED: ${OCR_ENABLED:-true}
      HF_HOME: /models/huggingface
      TORCH_HOME: /models/torch
    ports:
      - "8090:8090"
    volumes:
      - ai_models:/models

  frontend:
    build:
      context: ./frontend
    container_name: diplom-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"


volumes:
  postgres_data:
  backend_storage:
  ai_models:
